apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubiverse.name" . }}
  labels: {{- include "kubiverse.labels" . | nindent 4 }}
spec:
  selector: {{- include "kubiverse.selector" . | nindent 4 }}
  ports:
    - {name: http, port: 80, targetPort: http}
{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubiverse.name" . }}
  labels: {{- include "kubiverse.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: {storage: {{ .Values.persistence.size }}}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
